### ISSUE TITLE
 Can't install for Redmi note 8, android 9. Can you make it install on android 9?

### ISSUE THREAD

**Issue by datlm2** [Gokr-ble/M3U8downloader_Android#1]

**Comment by Gokr-ble** [comment]
Thanks for your support, I'm surprised that someone actually explored this project, which is an experimental one for my class. I'm also a student in university, so I'll try my best to learn some developing skills related and work on it, however I'm not sure when to fix this problem : )
As for this project, its minimal API version is 26 (Android 8), So I have tried to run and debug it on Android 9 Emulator (API 28) via Android Studio, it can launch successfully(but will not work properly). I've also test installing it on BlueStack Emulator (maybe Android 9), but it cannot install like what you described. One of the reasons is that I've used many Android 10 features to write file to Shared Area, and I'm working on its downward compatibility.
My suggestion is downloading the source code, compiling on Android Studio and running on real phone by Developer Mode.
Thanks!

**Comment by datlm2** [comment]
I'm a normal user, so I don't understand what the problem you are talking about? I went online looking for some apk file so I could hopefully download the m3u8 video on my phone and came across your project. But I still can't install it on my phone. Anyway, thanks for the reply <3

**Comment by Gokr-ble** [comment]
Well, if it is convenient for you to use PC, there is a far more powerful and advanced project, https://github.com/nilaoda/N_m3u8DL-CLI
I believe it will meet your requirements.
